# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - Musaif

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_cb66a1253006485f811f0a80dd67f215 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_13278ca9fa6744d19f25eb595cc98f13 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_cb66a1253006485f811f0a80dd67f215 }}/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'Musaif'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_a3da2dcc60a043a8a84ef1e1eb9dcd04 }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_cb66a1253006485f811f0a80dd67f215 }}/appsvc/staticsite:${{ github.sha }}'